// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: proto/map/v1/map.proto

package mapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PickupLat     float64                `protobuf:"fixed64,1,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLng     float64                `protobuf:"fixed64,2,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	DropoffLat    float64                `protobuf:"fixed64,3,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLng    float64                `protobuf:"fixed64,4,opt,name=dropoff_lng,json=dropoffLng,proto3" json:"dropoff_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_proto_map_v1_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{0}
}

func (x *GetRouteRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *GetRouteRequest) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *GetRouteRequest) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *GetRouteRequest) GetDropoffLng() float64 {
	if x != nil {
		return x.DropoffLng
	}
	return 0
}

type GetRouteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DistanceMeters  int32                  `protobuf:"varint,1,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Polyline        string                 `protobuf:"bytes,3,opt,name=polyline,proto3" json:"polyline,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_proto_map_v1_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{1}
}

func (x *GetRouteResponse) GetDistanceMeters() int32 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *GetRouteResponse) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *GetRouteResponse) GetPolyline() string {
	if x != nil {
		return x.Polyline
	}
	return ""
}

type GeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	mi := &file_proto_map_v1_map_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{2}
}

func (x *GeocodeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GeocodeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GeocodeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeResult) Reset() {
	*x = GeocodeResult{}
	mi := &file_proto_map_v1_map_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResult) ProtoMessage() {}

func (x *GeocodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResult.ProtoReflect.Descriptor instead.
func (*GeocodeResult) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{3}
}

func (x *GeocodeResult) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GeocodeResult) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeocodeResult) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*GeocodeResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeResponse) Reset() {
	*x = GeocodeResponse{}
	mi := &file_proto_map_v1_map_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse) ProtoMessage() {}

func (x *GeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse.ProtoReflect.Descriptor instead.
func (*GeocodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{4}
}

func (x *GeocodeResponse) GetResults() []*GeocodeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReverseGeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeRequest) Reset() {
	*x = ReverseGeocodeRequest{}
	mi := &file_proto_map_v1_map_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeRequest) ProtoMessage() {}

func (x *ReverseGeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeRequest.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{5}
}

func (x *ReverseGeocodeRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ReverseGeocodeRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ReverseGeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseGeocodeResponse) Reset() {
	*x = ReverseGeocodeResponse{}
	mi := &file_proto_map_v1_map_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseGeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseGeocodeResponse) ProtoMessage() {}

func (x *ReverseGeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseGeocodeResponse.ProtoReflect.Descriptor instead.
func (*ReverseGeocodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{6}
}

func (x *ReverseGeocodeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type FareEstimateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PickupLat     float64                `protobuf:"fixed64,1,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLng     float64                `protobuf:"fixed64,2,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	DropoffLat    float64                `protobuf:"fixed64,3,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLng    float64                `protobuf:"fixed64,4,opt,name=dropoff_lng,json=dropoffLng,proto3" json:"dropoff_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FareEstimateRequest) Reset() {
	*x = FareEstimateRequest{}
	mi := &file_proto_map_v1_map_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareEstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareEstimateRequest) ProtoMessage() {}

func (x *FareEstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareEstimateRequest.ProtoReflect.Descriptor instead.
func (*FareEstimateRequest) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{7}
}

func (x *FareEstimateRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *FareEstimateRequest) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *FareEstimateRequest) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *FareEstimateRequest) GetDropoffLng() float64 {
	if x != nil {
		return x.DropoffLng
	}
	return 0
}

type FareEstimateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalFare       int64                  `protobuf:"varint,1,opt,name=total_fare,json=totalFare,proto3" json:"total_fare,omitempty"`                     // e.g. 6000
	MitraServiceFee int64                  `protobuf:"varint,2,opt,name=mitra_service_fee,json=mitraServiceFee,proto3" json:"mitra_service_fee,omitempty"` // e.g. 5000
	PlatformFee     int64                  `protobuf:"varint,3,opt,name=platform_fee,json=platformFee,proto3" json:"platform_fee,omitempty"`               // e.g. 1000
	DistanceMeters  int32                  `protobuf:"varint,4,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FareEstimateResponse) Reset() {
	*x = FareEstimateResponse{}
	mi := &file_proto_map_v1_map_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareEstimateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareEstimateResponse) ProtoMessage() {}

func (x *FareEstimateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_v1_map_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareEstimateResponse.ProtoReflect.Descriptor instead.
func (*FareEstimateResponse) Descriptor() ([]byte, []int) {
	return file_proto_map_v1_map_proto_rawDescGZIP(), []int{8}
}

func (x *FareEstimateResponse) GetTotalFare() int64 {
	if x != nil {
		return x.TotalFare
	}
	return 0
}

func (x *FareEstimateResponse) GetMitraServiceFee() int64 {
	if x != nil {
		return x.MitraServiceFee
	}
	return 0
}

func (x *FareEstimateResponse) GetPlatformFee() int64 {
	if x != nil {
		return x.PlatformFee
	}
	return 0
}

func (x *FareEstimateResponse) GetDistanceMeters() int32 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

var File_proto_map_v1_map_proto protoreflect.FileDescriptor

const file_proto_map_v1_map_proto_rawDesc = "" +
	"\n" +
	"\x16proto/map/v1/map.proto\x12\x06map.v1\"\x91\x01\n" +
	"\x0fGetRouteRequest\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x01 \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\x02 \x01(\x01R\tpickupLng\x12\x1f\n" +
	"\vdropoff_lat\x18\x03 \x01(\x01R\n" +
	"dropoffLat\x12\x1f\n" +
	"\vdropoff_lng\x18\x04 \x01(\x01R\n" +
	"dropoffLng\"\x82\x01\n" +
	"\x10GetRouteResponse\x12'\n" +
	"\x0fdistance_meters\x18\x01 \x01(\x05R\x0edistanceMeters\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\x12\x1a\n" +
	"\bpolyline\x18\x03 \x01(\tR\bpolyline\"<\n" +
	"\x0eGeocodeRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"l\n" +
	"\rGeocodeResult\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"B\n" +
	"\x0fGeocodeResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.map.v1.GeocodeResultR\aresults\"Q\n" +
	"\x15ReverseGeocodeRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\";\n" +
	"\x16ReverseGeocodeResponse\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"\x95\x01\n" +
	"\x13FareEstimateRequest\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x01 \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\x02 \x01(\x01R\tpickupLng\x12\x1f\n" +
	"\vdropoff_lat\x18\x03 \x01(\x01R\n" +
	"dropoffLat\x12\x1f\n" +
	"\vdropoff_lng\x18\x04 \x01(\x01R\n" +
	"dropoffLng\"\xad\x01\n" +
	"\x14FareEstimateResponse\x12\x1d\n" +
	"\n" +
	"total_fare\x18\x01 \x01(\x03R\ttotalFare\x12*\n" +
	"\x11mitra_service_fee\x18\x02 \x01(\x03R\x0fmitraServiceFee\x12!\n" +
	"\fplatform_fee\x18\x03 \x01(\x03R\vplatformFee\x12'\n" +
	"\x0fdistance_meters\x18\x04 \x01(\x05R\x0edistanceMeters2\xa3\x02\n" +
	"\n" +
	"MapService\x12=\n" +
	"\bGetRoute\x12\x17.map.v1.GetRouteRequest\x1a\x18.map.v1.GetRouteResponse\x12:\n" +
	"\aGeocode\x12\x16.map.v1.GeocodeRequest\x1a\x17.map.v1.GeocodeResponse\x12O\n" +
	"\x0eReverseGeocode\x12\x1d.map.v1.ReverseGeocodeRequest\x1a\x1e.map.v1.ReverseGeocodeResponse\x12I\n" +
	"\fFareEstimate\x12\x1b.map.v1.FareEstimateRequest\x1a\x1c.map.v1.FareEstimateResponseB:Z8github.com/hodeifa/hyperlocal-backend/proto/map/v1;mapv1b\x06proto3"

var (
	file_proto_map_v1_map_proto_rawDescOnce sync.Once
	file_proto_map_v1_map_proto_rawDescData []byte
)

func file_proto_map_v1_map_proto_rawDescGZIP() []byte {
	file_proto_map_v1_map_proto_rawDescOnce.Do(func() {
		file_proto_map_v1_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_map_v1_map_proto_rawDesc), len(file_proto_map_v1_map_proto_rawDesc)))
	})
	return file_proto_map_v1_map_proto_rawDescData
}

var file_proto_map_v1_map_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_map_v1_map_proto_goTypes = []any{
	(*GetRouteRequest)(nil),        // 0: map.v1.GetRouteRequest
	(*GetRouteResponse)(nil),       // 1: map.v1.GetRouteResponse
	(*GeocodeRequest)(nil),         // 2: map.v1.GeocodeRequest
	(*GeocodeResult)(nil),          // 3: map.v1.GeocodeResult
	(*GeocodeResponse)(nil),        // 4: map.v1.GeocodeResponse
	(*ReverseGeocodeRequest)(nil),  // 5: map.v1.ReverseGeocodeRequest
	(*ReverseGeocodeResponse)(nil), // 6: map.v1.ReverseGeocodeResponse
	(*FareEstimateRequest)(nil),    // 7: map.v1.FareEstimateRequest
	(*FareEstimateResponse)(nil),   // 8: map.v1.FareEstimateResponse
}
var file_proto_map_v1_map_proto_depIdxs = []int32{
	3, // 0: map.v1.GeocodeResponse.results:type_name -> map.v1.GeocodeResult
	0, // 1: map.v1.MapService.GetRoute:input_type -> map.v1.GetRouteRequest
	2, // 2: map.v1.MapService.Geocode:input_type -> map.v1.GeocodeRequest
	5, // 3: map.v1.MapService.ReverseGeocode:input_type -> map.v1.ReverseGeocodeRequest
	7, // 4: map.v1.MapService.FareEstimate:input_type -> map.v1.FareEstimateRequest
	1, // 5: map.v1.MapService.GetRoute:output_type -> map.v1.GetRouteResponse
	4, // 6: map.v1.MapService.Geocode:output_type -> map.v1.GeocodeResponse
	6, // 7: map.v1.MapService.ReverseGeocode:output_type -> map.v1.ReverseGeocodeResponse
	8, // 8: map.v1.MapService.FareEstimate:output_type -> map.v1.FareEstimateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_map_v1_map_proto_init() }
func file_proto_map_v1_map_proto_init() {
	if File_proto_map_v1_map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_map_v1_map_proto_rawDesc), len(file_proto_map_v1_map_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_map_v1_map_proto_goTypes,
		DependencyIndexes: file_proto_map_v1_map_proto_depIdxs,
		MessageInfos:      file_proto_map_v1_map_proto_msgTypes,
	}.Build()
	File_proto_map_v1_map_proto = out.File
	file_proto_map_v1_map_proto_goTypes = nil
	file_proto_map_v1_map_proto_depIdxs = nil
}
