// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: proto/location/v1/location.proto

package location

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationService_GetDriversWithinRadius_FullMethodName = "/location.v1.LocationService/GetDriversWithinRadius"
	LocationService_GetNearbyActive_FullMethodName        = "/location.v1.LocationService/GetNearbyActive"
)

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationServiceClient interface {
	GetDriversWithinRadius(ctx context.Context, in *GetDriversWithinRadiusRequest, opts ...grpc.CallOption) (*GetDriversWithinRadiusResponse, error)
	GetNearbyActive(ctx context.Context, in *GetNearbyActiveRequest, opts ...grpc.CallOption) (*GetNearbyActiveResponse, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) GetDriversWithinRadius(ctx context.Context, in *GetDriversWithinRadiusRequest, opts ...grpc.CallOption) (*GetDriversWithinRadiusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriversWithinRadiusResponse)
	err := c.cc.Invoke(ctx, LocationService_GetDriversWithinRadius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) GetNearbyActive(ctx context.Context, in *GetNearbyActiveRequest, opts ...grpc.CallOption) (*GetNearbyActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNearbyActiveResponse)
	err := c.cc.Invoke(ctx, LocationService_GetNearbyActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility.
type LocationServiceServer interface {
	GetDriversWithinRadius(context.Context, *GetDriversWithinRadiusRequest) (*GetDriversWithinRadiusResponse, error)
	GetNearbyActive(context.Context, *GetNearbyActiveRequest) (*GetNearbyActiveResponse, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationServiceServer struct{}

func (UnimplementedLocationServiceServer) GetDriversWithinRadius(context.Context, *GetDriversWithinRadiusRequest) (*GetDriversWithinRadiusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriversWithinRadius not implemented")
}
func (UnimplementedLocationServiceServer) GetNearbyActive(context.Context, *GetNearbyActiveRequest) (*GetNearbyActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNearbyActive not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}
func (UnimplementedLocationServiceServer) testEmbeddedByValue()                         {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_GetDriversWithinRadius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriversWithinRadiusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetDriversWithinRadius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetDriversWithinRadius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetDriversWithinRadius(ctx, req.(*GetDriversWithinRadiusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_GetNearbyActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNearbyActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetNearbyActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_GetNearbyActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetNearbyActive(ctx, req.(*GetNearbyActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "location.v1.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDriversWithinRadius",
			Handler:    _LocationService_GetDriversWithinRadius_Handler,
		},
		{
			MethodName: "GetNearbyActive",
			Handler:    _LocationService_GetNearbyActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/location/v1/location.proto",
}
