// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: proto/customer/v1/customer.proto

package customer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest — hanya menerima nomor HP.
// Field 'name' sengaja tidak disertakan (reserved) karena:
// (1) nama diminta di layar terpisah (PATCH /profile) sesuai blueprint-ui.md
// (2) /register bersifat stateless, tidak ada INSERT ke DB di sini
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // Format E.164, wajib prefix +62 (divalidasi di Gateway)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_customer_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_customer_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// RegisterResponse — dikembalikan setelah OTP berhasil dikirim (simulasi di Sprint 4)
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                     // Pesan sukses, misal: "OTP berhasil dikirim"
	HasDriverRole bool                   `protobuf:"varint,2,opt,name=has_driver_role,json=hasDriverRole,proto3" json:"has_driver_role,omitempty"` // true jika nomor HP juga terdaftar di tabel drivers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_customer_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_customer_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHasDriverRole() bool {
	if x != nil {
		return x.HasDriverRole
	}
	return false
}

var File_proto_customer_v1_customer_proto protoreflect.FileDescriptor

const file_proto_customer_v1_customer_proto_rawDesc = "" +
	"\n" +
	" proto/customer/v1/customer.proto\x12\vcustomer.v1\":\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumberJ\x04\b\x02\x10\x03\"T\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x0fhas_driver_role\x18\x02 \x01(\bR\rhasDriverRole2Z\n" +
	"\x0fCustomerService\x12G\n" +
	"\bRegister\x12\x1c.customer.v1.RegisterRequest\x1a\x1d.customer.v1.RegisterResponseBBZ@github.com/hodeifa/hyperlocal-backend/proto/customer/v1;customerb\x06proto3"

var (
	file_proto_customer_v1_customer_proto_rawDescOnce sync.Once
	file_proto_customer_v1_customer_proto_rawDescData []byte
)

func file_proto_customer_v1_customer_proto_rawDescGZIP() []byte {
	file_proto_customer_v1_customer_proto_rawDescOnce.Do(func() {
		file_proto_customer_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_customer_v1_customer_proto_rawDesc), len(file_proto_customer_v1_customer_proto_rawDesc)))
	})
	return file_proto_customer_v1_customer_proto_rawDescData
}

var file_proto_customer_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_customer_v1_customer_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: customer.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: customer.v1.RegisterResponse
}
var file_proto_customer_v1_customer_proto_depIdxs = []int32{
	0, // 0: customer.v1.CustomerService.Register:input_type -> customer.v1.RegisterRequest
	1, // 1: customer.v1.CustomerService.Register:output_type -> customer.v1.RegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_customer_v1_customer_proto_init() }
func file_proto_customer_v1_customer_proto_init() {
	if File_proto_customer_v1_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_customer_v1_customer_proto_rawDesc), len(file_proto_customer_v1_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_customer_v1_customer_proto_goTypes,
		DependencyIndexes: file_proto_customer_v1_customer_proto_depIdxs,
		MessageInfos:      file_proto_customer_v1_customer_proto_msgTypes,
	}.Build()
	File_proto_customer_v1_customer_proto = out.File
	file_proto_customer_v1_customer_proto_goTypes = nil
	file_proto_customer_v1_customer_proto_depIdxs = nil
}
